name: Lint, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: install gcloud cli
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true


      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run black
        run: black .
      
      - name: Run autopep8
        run: autopep8 --in-place --aggressive --aggressive . --recursive
      
      - name: Run isort
        run: isort .

      - name: Run flake8
        run: flake8 .

      # - name: Run tests 
      #   run: pytest ./tests

      - name: Build and Deploy
        env: 
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/portfolio/portfolio:latest .
          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/portfolio/portfolio:latest


      

