name: Lint, Test and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run black
        run: black .
      
      - name: lint toddbo
        run:  pylint /toddbo

      - name: lint app
        run:  pylint /app

      - name: Run tests 
        run: pytest ./tests

      - name: Build image
        run: echo "Building the image"
        
      - name: Deploy to Google Registry
        run: echo "Deploying to Google Registry"

      

