OPENAI_API_KEY = "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"

[pinecone]
api_key = "96dfe80a-b2d4-492d-997a-1c61c37f3d64"
index = "resume"

[openai]
OPENAI_API_KEY = "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"
temperature = 0.2
embedding_model = 'text-embedding-ada-002'
generation_model = "gpt-4"

[cookie]
expiry_days = 1
key = "some_signature_key"
name = "some_cookie_name"

[credentials]
usernames = { recruiter = {email = "marino.todd@gmail.com", name = "Recruiter", password = "$2b$12$aOe0uy8cDRGeM6uOHUfiueeSI93jSOa21G6Fq6rA7oBh2lmYuaGcS"}}

[preauthorized]
emails = ["todd.adam.michael.marino@gmail.com"]